-- no time for migrations, wip

CREATE TABLE IF NOT EXISTS urls(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short VARCHAR(255),
    origin VARCHAR(255),
    ip VARCHAR,
    agent TEXT,
    hits BIGINT
);